[phases.setup]
nixPkgs = ["...", "apache2", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "mkdir -p /app/logs /app/uploads",
  "chmod 755 /app/logs /app/uploads"
]

[phases.build]
cmds = [
  "chmod +x /app/deploy.sh",
  "echo 'Build completed'"
]

[start]
cmd = "apache2-foreground"